export interface LanguageConfig {
  name: string;
  value: string;
}

export const LANGUAGES: LanguageConfig[] = [
  { name: 'English', value: 'en' },
  { name: 'Albanian', value: 'sq' },
  { name: 'Arabic', value: 'ar' },
  { name: 'Armenian', value: 'hy' },
  { name: 'Azerbaijani', value: 'az' },
  { name: 'Basque', value: 'eu' },
  { name: 'Belarusian', value: 'be' },
  { name: 'Bengali', value: 'bn' },
  { name: 'Bulgarian', value: 'bg' },
  { name: 'Catalan', value: 'ca' },
  { name: 'Chinese (Simplified)', value: 'zh-CN' },
  { name: 'Chinese (Traditional)', value: 'zh-TW' },
  { name: 'Croatian', value: 'hr' },
  { name: 'Czech', value: 'cs' },
  { name: 'Danish', value: 'da' },
  { name: 'Dutch', value: 'nl' },
  { name: 'Esperanto', value: 'eo' },
  { name: 'Estonian', value: 'et' },
  { name: 'Filipino', value: 'tl' },
  { name: 'Finnish', value: 'fi' },
  { name: 'French', value: 'fr' },
  { name: 'Galician', value: 'gl' },
  { name: 'Georgian', value: 'ka' },
  { name: 'German', value: 'de' },
  { name: 'Greek', value: 'el' },
  { name: 'Gujarati', value: 'gu' },
  { name: 'Haitian (Creole)', value: 'ht' },
  { name: 'Hebrew', value: 'iw' },
  { name: 'Hindi', value: 'hi' },
  { name: 'Hungarian', value: 'hu' },
  { name: 'Icelandic', value: 'is' },
  { name: 'Indonesian', value: 'id' },
  { name: 'Irish', value: 'ga' },
  { name: 'Italian', value: 'it' },
  { name: 'Japanese', value: 'ja' },
  { name: 'Kannada', value: 'kn' },
  { name: 'Korean', value: 'ko' },
  { name: 'Latin', value: 'la' },
  { name: 'Latvian', value: 'lv' },
  { name: 'Lithuanian', value: 'lt' },
  { name: 'Macedonian', value: 'mk' },
  { name: 'Malay', value: 'ms' },
  { name: 'Maltese', value: 'mt' },
  { name: 'Persian', value: 'fa' },
  { name: 'Polish', value: 'pl' },
  { name: 'Portuguese', value: 'pt' },
  { name: 'Romanian', value: 'ro' },
  { name: 'Russian', value: 'ru' },
  { name: 'Serbian', value: 'sr' },
  { name: 'Slovak', value: 'sk' },
  { name: 'Slovenian', value: 'sl' },
  { name: 'Spanish', value: 'es' },
  { name: 'Swahili', value: 'sw' },
  { name: 'Swedish', value: 'sv' },
  { name: 'Tamil', value: 'ta' },
  { name: 'Telugu', value: 'te' },
  { name: 'Thai', value: 'th' },
  { name: 'Turkish', value: 'tr' },
  { name: 'Ukrainian', value: 'uk' },
  { name: 'Urdu', value: 'ur' },
  { name: 'Vietnamese', value: 'vi' },
  { name: 'Welsh', value: 'cy' },
  { name: 'Yiddish', value: 'yi' }
];
