name: 'pre-release'

# Updates the "latest" tag to the current head when new pushes are
# made to main and updates the "Latest Development Build" release with
# artifacts from this revision

on:
  push:
    branches: [main]

jobs:
  pre-release:
    name: 'Pre Release'
    runs-on: 'ubuntu-latest'
    permissions: 'write-all'

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Build project
        run: npm run build

      - name: Archive build artifacts
        run: |
          pushd .output/chrome-mv3/ && zip -r ../../nrk-dual-subs-chrome.zip ./* && popd

      - name: Create prerelease
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          title: 'Latest Development Build'
          automatic_release_tag: 'latest'
          prerelease: true
          files: |
            nrk-dual-subs-chrome.zip
