name: Publish package

on:
  push:
    tags: ['*/v*']

jobs:
  release:
    name: 'Release'
    runs-on: 'ubuntu-latest'
    permissions: 'write-all'

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: node

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install
        run: pnpm install

      - name: Build project
        run: pnpm build

      - name: Archive build artifacts
        if: ${{ steps.release.outputs.release_created }}
        run: |
          pushd .output/chrome-mv3/ && zip -r ../../nrk-dual-subs-chrome.zip ./* && popd

      - name: Upload release artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ steps.release.outputs.tag_name }} nrk-dual-subs-chrome.zip

      - name: Upload & release
        if: ${{ steps.release.outputs.release_created }}
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: nrk-dual-subs-chrome.zip
          extension-id: ${{ secrets.CHROME_STORE_APP_ID }}
          client-id: ${{ secrets.CHROME_STORE_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_STORE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_STORE_REFRESH_TOKEN }}
          publish: true
