name: Check and prepare PR

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

permissions:
  checks: 'write'
  contents: 'write'
  pull-requests: 'read'

jobs:
  lint_title:
    name: Conventional commit PR title
    runs-on: ubuntu-latest

    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
