name: Release Please

on:
  push:
    branches: [main]

jobs:
  release-please:
    name: Check for release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4.2.2
      - uses: actions/create-github-app-token@v1.11.5
        id: app-token
        with:
          app-id: ${{ secrets.RELEASE_BOT_APP_ID }}
          private-key: ${{ secrets.RELEASE_BOT_PRIVATE_KEY }}
      - uses: googleapis/release-please-action@v4.1.1
        with:
          token: ${{ steps.app-token.outputs.token }}
